import './globals.css'; 
import type { Metadata } from 'next'; 
import { Inter } from 'next/font/google'; 
import ClientLayout from '@/components/ClientLayout'; 
import { useEffect, useState } from "react";



const inter = Inter({ subsets: ['latin'] }); 

export const metadata: Metadata = { 
  title: 'Create Next App', 
  description: 'Generated by create next app', 
}; 

export default function RootLayout({ children }: { children: React.ReactNode }) { 


  return ( 
    <html lang="en" className="light"> {/* FIXED: Applies theme class to <html> */}
      <link rel="preconnect" href="https://fonts.googleapis.com"/> 
      <link rel="preconnect" href="https://fonts.gstatic.com" /> 
      <link href="https://fonts.googleapis.com/css2?family=ADLaM+Display&display=swap" rel="stylesheet"/> 

      <body className='bg-white'> 
        <ClientLayout>{children}</ClientLayout> 
      </body> 
    </html> 
  ); 
}
